shopsys/apps/catalog/urls.py
# encoding:utf-8
from django.conf.urls import  url
#from . import views
from shopsys.apps.catalog import  views

# urlpatterns=[
#     url(r'^$',views.index,{'template_name':'catalog/index.html'},'catalog_home'),
#     url(r'^category/(?P<category_slug>[-\w]+)/$',views.show_category,{'template_name':'catalog/category.html'},'catalog_category'),
#     url(r'^product/(?P<product_slug>[-\w]+)/$',views.show_product,{'template_name':'catalog/product.html'},'catalog_product'),
# ]

urlpatterns = [
    url(r'^', views.index,name='catalog_home'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category,name='catalog_category'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, name= 'catalog_product'),
]

shopsys/apps/plan/urls.py
from django.conf.urls import  url
from shopsys.apps.plan import  views


urlpatterns = [
    url(r'^plan/$', views.plan,name='plan'),
    url(r'^planlist/$', views.planlist,name='planlist'),
    url(r'^plandetail/$', views.plandetail,name='plandetail'),
    url(r'^contactlist/$',views.contactlist.as_view(),name='contactlist'),
    url(r'^contactdetail/(?P<pk>[0-9]+)$',views.contact_detail,name='contactdetail'),
    url(r'^planelist/$', views.PlaneList.as_view(),name='planelist'),
    url(r'^trainlist/$', views.TrainList.as_view(),name='trainlist'),
    url(r'^hotellist/$', views.HotelList.as_view(),name='hotellist'),
    url(r'^plancontact/$', views.contactview.as_view(),name='plancontact'),
]

shopsys/apps/regist/urls.py
from django.conf.urls import  url
from shopsys.apps.regist import  views


# urlpatterns=[
#     url(r'^$',views.index,{'template_name':'catalog/index.html'},'catalog_home'),
#     url(r'^category/(?P<category_slug>[-\w]+)/$',views.show_category,{'template_name':'catalog/category.html'},'catalog_category'),
#     url(r'^product/(?P<product_slug>[-\w]+)/$',views.show_product,{'template_name':'catalog/product.html'},'catalog_product'),
# ]

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^regist/$', views.regist,name='regist'),
    url(r'^login/$', views.login,name='login'),
    url(r'^user/$', views.user,name='user'),
    url(r'^maps/$', views.maps,name='map'),
    url(r'^contact/$', views.contact,name='contact'),
    url(r'^contactadd/$',views.contact_add,name='contact_add'),
    url(r'^notification/$', views.notificaiton,name='notification'),
    url(r'^logout/$', views.logout_view,name='logout'),
]

shopsys/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^regist/',include('shopsys.apps.regist.urls')),
    url(r'^catalog/',include('shopsys.apps.catalog.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shopsys/apps/regist/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    name=models.CharField("姓名",max_length=50)
    loginname=models.CharField("登录名",max_length=30,unique=True)
    password=models.CharField("密码",max_length=30)
    telephone=models.CharField("手机",max_length=30)
    weixin=models.CharField("微信号",max_length=50)
    description=models.TextField("描述")
    is_active=models.BooleanField("是否有效",default=True)
    regist_at=models.DateTimeField("注册时间",auto_now_add=True)
    update_at=models.DateTimeField("修改时间",auto_now=True)

    class Meta:
        db_table='customer'
        ordering=['-regist_at']
        verbose_name = '客户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('regist_customer',args=(self.slug,))

class Contact(models.Model):
    name = models.CharField("姓名", max_length=50)
    cardid = models.CharField("身份证号", max_length=30)
    telephone = models.CharField("手机", max_length=30)
    weixin = models.CharField("微信号", max_length=50)
    age=models.IntegerField("年龄")
    sex=models.IntegerField("性别",choices=((1,'男'),(0,'女'),))
    description = models.TextField("描述")
    is_active = models.BooleanField("是否有效", default=True)
    create_at = models.DateTimeField("新增时间", auto_now_add=True)
    update_at = models.DateTimeField("修改时间", auto_now=True)
    customer=models.ForeignKey(User)

    class Meta:
        db_table = 'contact'
        ordering = ['-create_at']
        verbose_name = '联系人'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('regist_contact', args=(self.slug,))

shopsys/apps/catalog/forms.py
# encoding:utf-8
from django import forms
from .models import Product

class ProductAdminForm(forms.ModelForm):
    class Meta:
        model=Product
        exclude=[]
    def clean_price(self):
        if self.cleaned_data['price']<=0:
            raise forms.ValidationError('价格必须大于0')
        return self.cleaned_data['price']

shopsys/apps/regist/forms.py
# encoding:utf-8
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(CustomerForm, self).clean()
        value = cleaned_data.get("name")
        try:
            Customer.objects.get(name=value)
            self.errors["name"] = self.error_class(["%sx客户已存在" % value])
        except Customer.DoesNotExist:
            pass
        return cleaned_data

    class Meta:
        model = Customer
        exclude = {"id", }

# Create your views here.
#用户注册表单
class UserForm(forms.Form):
    email  = forms.EmailField(label="邮箱",max_length=50)
    username  = forms.CharField(label='用 户 名',max_length=50)
    password1 = forms.CharField(label='密   码',widget=forms.PasswordInput())
    password2 = forms.CharField(label='确认密码',widget=forms.PasswordInput())

#用户登录表单
class LoginForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=50)
    password = forms.CharField(label='密  码',widget=forms.PasswordInput())

#联系人表单
class ContactForm(forms.Form):
    name = forms.CharField(label="姓名", max_length=50)
    cardid = forms.CharField(label="身份证号", max_length=30)
    telephone = forms.CharField(label="手机", max_length=30)
    weixin = forms.CharField(label="微信号", max_length=50)
    age = forms.IntegerField(label="年龄")
    sex = forms.IntegerField(label="性别")

shopsys/apps/catalog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product

# Create your views here.

def index(request):
    page_title='产品分类目录'
    username= request.session.get('username',default=None)
    return render(request,'catalog/index.html',locals())

def show_category(request,category_slug):
    c = get_object_or_404(Category,slug=category_slug)
    products=c.product_set.all()
    page_title=c.name
    meta_keywords=c.meta_keywords
    meta_description=c.meta_description
    return render(request,'catalog/category.html',locals())

def show_product(request,product_slug):
    p = get_object_or_404(Product,slug=product_slug)
    categories=p.categories.filter(is_active=True)
    page_title=p.name
    meta_keywords=p.meta_keywords
    meta_description=p.meta_description
    return render(request,'catalog/products.html',locals())

shopsys/apps/plan/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404
from shopsys.apps.plan.forms import  PlanForm,PlaneForm,TrainForm,HotelForm,Plan_ContactForm
from django.http import HttpRequest,HttpResponse,HttpResponseRedirect,JsonResponse
from shopsys.apps.plan.models import Plan,Plane_plan,Hotel_plan,Train_plan,Train,Hotel,Plane
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from shopsys.apps.regist.models import Contact
from rest_framework.views import APIView
from rest_framework.response import Response
from shopsys.apps.plan.resource import planserializer,trainserializer,hotelserializer,contactserializer
from rest_framework.decorators import api_view
from django.views.generic import View
from rest_framework import  status
from rest_framework import generics

# Create your views here.
@login_required
def plan(request):
    username = request.session.get('username', default=None)


    Method = request.method
    if Method == 'POST':
        #如果有post提交的动作，就将post中的数据赋值给uf，供该函数使用

        uf = PlanForm(request.POST)

        if uf.is_valid():
            name=uf.cleaned_data['fromcity']+uf.cleaned_data['tocity']+uf.cleaned_data['start_at'].strftime("%Y%m%d")
            fromcity = uf.cleaned_data['fromcity']
            tocity = uf.cleaned_data['tocity']
            start_at=uf.cleaned_data['start_at']
            back_at = uf.cleaned_data['back_at']
            traffictype = uf.cleaned_data['traffictype']
            hotletype = uf.cleaned_data['hotletype']
            target = uf.cleaned_data['target']
            targetcoordinate = uf.cleaned_data['targetcoordinate']
            ifback = uf.cleaned_data['ifback']
            description = uf.cleaned_data['description']
            is_active=1
            customerid=request.session.get('userid', default=1)
            #customerid=1

            planAdd = Plan.objects.create(name=name,fromcity=fromcity,tocity=tocity,start_at=start_at,back_at=back_at,traffictype=traffictype,hotletype=hotletype,target=target,targetcoordinate=targetcoordinate,ifback=ifback,description=description,is_active=is_active,customer_id=customerid)
            response = HttpResponseRedirect('/plan/plandetail/?planid='+str(planAdd.id))
            return response

            #return HttpResponse('/plan/plandetail/?planid='+str(planAdd.id))
            #return render (request,'plan/plan_detail.html',locals())

    else:
        uf = PlanForm()
    return render (request,'plan/plan.html',locals())

@login_required
def planlist(request):
    username = request.session.get('username', default=None)
    customerid = request.session.get('userid', default=None)
    plan_list=Plan.objects.filter(customer_id=customerid).order_by("-id")
    paginator = Paginator(plan_list, 6)
    page = request.GET.get('page')
    try:
        plans = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        plans = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        plans = paginator.page(paginator.num_pages)
    return render (request,'plan/planlist.html',locals())

@login_required
def plandetail(request):
    planid = request.GET.get('planid')
    username = request.session.get('username', default=None)
    customerid = request.session.get('userid', default=None)
    plan=Plan.objects.get(id=planid)
    fromcity=plan.fromcity
    tocity=plan.tocity
    planes=Plane.objects.filter(fromcity=fromcity, tocity=tocity)
    trains=Train.objects.filter(fromstation=fromcity,tostation=tocity)
    hotels=Hotel.objects.filter(city=tocity)
    contacts=Contact.objects.filter(customer=customerid)
    return render (request,'plan/plan_detail_3.html',locals())


#飞机

#飞机列表类
class Cart_plane(object):
    def __init__(self, *args, **kwargs):
        self.items = []

    def add_plane(self,plan,plane):
        contact_list=plan.contact.all()
        for item in contact_list:
            self.items.append(Plane(id=plane.id, planid=plan.id,contactid=item.customer_id))
        print (self.items)
        return  self.items

#显示飞机票购物车
def view_cartplane(request):
    cart_plane = request.session.get("cart_plane",None)
    if not cart_plane:
        cart_plane = Cart_plane()
        request.session["cart_plane"] = cart_plane
    return render(request,'plan/plan_detail_2.html',locals())

#添加到飞机票购物车
def add_to_cartplane(request,id):
    plane = Plane.objects.get(id = id)
    planid = request.GET.get('planid')
    plan= Plan.objects.get(id=planid)
    cart = request.session.get("cart_plane",None)
    if not cart:
        cart = Cart_plane()
        request.session["cart_plane"] = cart
        cart.add_plane(plane,plan)
        request.session['cart_plane'] = cart
    return view_cartplane(request)

#清空飞机票购物车
def clean_cartplane(request):
    request.session["cart_plane"] = Cart_plane()
    return view_cartplane(request)

#火车
#火车列表类
class Cart_train(object):
    def __init__(self, *args, **kwargs):
        self.items = []

    def add_train(self,plan,train):
        contact_list=plan.contact.all()
        for item in contact_list:
            self.items.append(Train(id=train.id, planid=plan.id,contactid=item.customer_id))
        print (self.items)
        return  self.items

#显示火车票购物车
def view_carttrain(request):
    cart_train = request.session.get("cart_train",None)
    if not cart_train:
        cart_train = Cart_train()
        request.session["cart_train"] = cart_train
    return render(request,'plan/plan_detail.html',locals())

#添加到火车票购物车
def add_to_carttrain(request,id):
    train = Train.objects.get(id = id)
    planid = request.GET.get('planid')
    plan = Plan.objects.get(id=planid)
    cart = request.session.get("cart_train",None)
    if not cart:
        cart = Cart_train()
        request.session["cart_train"] = cart
        cart.add_train(train,plan)
        request.session['cart_train'] = cart
    return view_carttrain(request)

#清空火车票购物车
def clean_carttrain(request):
    request.session["cart_train"] = Cart_train()
    return view_carttrain(request)

#宾馆
#宾馆列表类
class Cart_hotel(object):
    def __init__(self, *args, **kwargs):
        self.items = []

    def add_hotel(self,plan,hotel):
        contact_list=plan.contact.all()
        for item in contact_list:
            self.items.append(Hotel(id=hotel.id, planid=plan.id,contactid=item.customer_id))
        print (self.items)
        return  self.items

#显示宾馆购物车
def view_carthotel(request):
    cart_hotel = request.session.get("cart_hotel",None)
    if not cart_hotel:
        cart_hotel = Cart_hotel()
        request.session["cart_hotel"] = cart_hotel
    return render(request,'plan/plan_detail.html',locals())

#添加到宾馆购物车
def add_to_carthotel(request,id):
    hotel = Hotel.objects.get(id = id)
    planid = request.GET.get('planid')
    plan = Plan.objects.get(id=planid)
    cart = request.session.get("cart_hotel",None)
    if not cart:
        cart = Cart_hotel()
        request.session["cart_hotel"] = cart
        cart.add_hotel(hotel,plan)
        request.session['cart_hotel'] = cart
    return view_carthotel(request)

#清空宾馆购物车
def clean_carthotel(request):
    request.session["cart_hotel"] = Cart_hotel()
    return view_carthotel(request)


class PlaneList(APIView):
    def get(self, request, format=None):
        planes = Plane.objects.all()
        plansserializer = planserializer(planes, many=True)
        return Response(plansserializer.data)

class TrainList(APIView):
    def get(self, request, format=None):
        trains = Train.objects.all()
        trainsserializer = trainserializer(trains, many=True)
        return Response(trainsserializer.data)

class HotelList(APIView):
    def get(self, request, format=None):
        hotels = Hotel.objects.all()
        hotelsserializer = hotelserializer(hotels, many=True)
        return Response(hotelsserializer.data)

plan_field_list = ['id', 'plan_id', {'contact': ['id', 'name']}]
#获取当前用户的联系人列表
class contactlist(APIView):
    def get(self, request, format=None):
        customerid = request.session.get('userid', default=None)
        #contacts = Contact.objects.filter(customer=customerid)
        contacts = Contact.objects.all()
        serializer = contactserializer(contacts, many=True)
        return Response(serializer.data)
    def post(self,request,format=None):
        customer_list=request.POST.getlist('chk')
        planid=request.POST.get('planid')
        plan=Plan.objects.get(id=planid)
        plan.contact.clear()
        plan.contact.add(*customer_list)
        contact=plan.contact.all()
        serializer = contactserializer(contact, many=True)
        return Response(serializer.data)


class contactview(View):
    def get(self, request):
        _list = Plan.objects.all()
        _rtn = [i.serializable_values(plan_field_list) for i in _list]
        result = {"data": _rtn}
        return JsonResponse(result)


#获取某个联系人操作
@api_view(['GET','PUT','DELETE'])
def contact_detail(request,pk):
    try:
        contacts = Contact.objects.get(pk=pk)
    except Contact.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = contactserializer(contacts)
        return Response(serializer.data)
    elif request.method=='PUT':
        serializer = contactserializer(contacts,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    elif request.method=='DELETE':
        contacts.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

shopsys/templates/regist/contact.html
{% extends "registbase.html" %}
{% load staticfiles %}
{% block tree %}
	<div class="sidebar" data-background-color="white" data-active-color="danger">

    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="/regist/" class="simple-text">
                    前站信息
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="/plan/plan/">
                        <i class="ti-panel"></i>
                        <p>我的行程</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/">
                        <i class="ti-panel"></i>
                        <p>用户视图</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/user/">
                        <i class="ti-user"></i>
                        <p>用户属性</p>
                    </a>
                </li>
                <li>
                    <a href="/plan/planlist/">
                        <i class="ti-view-list-alt"></i>
                        <p>行程列表</p>
                    </a>
                </li>
                <li class="active">
                    <a href="/regist/contact/">
                        <i class="ti-text"></i>
                        <p>联系人</p>
                    </a>
                </li>
                 <li>
                    <a href="/regist/maps/">
                        <i class="ti-map"></i>
                        <p>地图</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/notification">
                        <i class="ti-bell"></i>
                        <p>小贴士</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
{% endblock %}
{% block content %}
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">

                            <div class="content table-responsive table-full-width">
                                <table class="table table-striped">
                                    <thead>
                                        <th>ID</th>
                                    	<th>姓名</th>
                                    	<th>身份证号</th>
                                    	<th>手机</th>
                                    	<th>微信号</th>
                                        <th>年龄</th>
                                        <th>性别</th>
                                    </thead>

                                    <tbody>
                                     {% for line in contacts %}
                                        <tr>
                                        	<td>{{ line.id }}</td>
                                        	<td>{{ line.name }}</td>
                                        	<td>{{ line.cardid }}</td>
                                        	<td>{{ line.telephone }}</td>
                                        	<td>{{ line.weixin }}</td>
                                            <td>{{ line.age }}</td>
                                        	<td>{{ line.get_sex_display}}</td>

                                        </tr>
                                     {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            第 {{ contacts.number }} 页，共 {{ contacts.paginator.num_pages }}页.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">下一页</a>
        {% endif %}
    </span>
    <button onclick="openWin('contact_add')" class="btn btn-info btn-fill btn-wd">新增联系人</button>
</div>

 <div id="contact_add" style="display: none; POSITION: absolute;z-index:5555; left: 50%; top: 50%; width: 500px; height: 500px; margin-left: -300px; margin-top: -200px; border: 1px solid #888; background-color: #FFF; padding-left: 10px; padding-right: 10px;">
         <form  method="post" action="/regist/contactadd/">
            {% csrf_token %}
                <div class="form-group">
                    <img src="{% static "/img/5-140FG95152.png" %}" width="50" height="30" onClick="closeWin('contact_add')" style="position:absolute; right:10px; top:5px; "><br>
                    <h2>新增联系人</h2>
                      <table width="97%">
                          <tr>
                            <td width="20%" height="60px"><label>姓  名</label></td>
                            <td height="40px"><input id="text_" type="text" name="name" class="form-control border-input" placeholder="张三"></td>
                          </tr>
                           <tr>
                            <td width="20%" height="60px"><label>身份证</label></td>
                            <td><input id="cardid" type="text" name="cardid" class="form-control border-input" placeholder="64111111111111111"></td>
                          </tr>
                          <tr>
                            <td width="20%" height="60px"><label>手机号码</label></td>
                            <td><input id="telephone" type="tel" name="telephone" class="form-control border-input" placeholder="139088888888"></td>
                          </tr>
                          <tr>
                            <td width="20%" height="60px"><label>微信号</label></td>
                            <td><input id="weixin" type="text" name="weixin" class="form-control border-input" placeholder="zang88888"></td>
                          </tr>
                          <tr>
                            <td width="20%" height="60px"><label>年龄</label></td>
                            <td><input id="age" type="number" name="age" class="form-control border-input" placeholder="40"></td>
                          </tr>
                          <tr>
                            <td width="20%" height="60px"><label>性别</label></td>
                            <td>
                              <input type="radio" name="sex" id="r1" value=1 />男
                              <input type="radio" name="sex" id="r2" value=0 />女
                            </td>
                          </tr>
                        </table>
                </div>
              <div class="text-center">
                <button type="submit" class="btn btn-info btn-fill btn-wd">提交</button>
            </div>
            </form>

 </div>
 {% endblock %}

shopsys/templates/regist/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
<div class="wrapper">

    <!--左侧目录的替换区-->
    {% block tree %}{% endblock %}

      <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                     <a class="navbar-brand" href="#">服务信息</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                                <i class="ti-panel"></i>
								<p>欢迎【】</p>
                            </a>
                        </li>
                        <li >
                              <a href="#" >
                                <i class="ti-bell"></i>
                                <p>登录</p>
	                          </a>
                       	</li>
						<li>
                            <a href="#">
								<i class="ti-settings"></i>
								<p>注销</p>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

<!--右侧内容的替换区-->
{% block content %}{% endblock %}

<!--底部内容-->
        <footer class="footer">
            <div class="container-fluid">
                <div class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script>, 制作单位：西安前站信息技术有限公司
                </div>
            </div>
        </footer>

    </div>
</div>



{% endblock %}

shopsys/templates/regist/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <title>
        {% block title %}
            {% if page_title %} {{ page_title }}-{% endif %}{{ site_name }}
        {% endblock %}
    </title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="{{ meta_keywords }}" />
	    <meta name="description" content="{{ meta_description }}" />
        <!--  login and regist     -->
        <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet" />
        <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
        <link rel="stylesheet" type="text/css" href="{% static  "css/demo.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{%  static "css/style.css" %}" />
		<link rel="stylesheet" type="text/css" href="{%  static "css/animate-custom.css" %}" />
    </head>
    <body>
    <div class="container-fluid" style="background-color: lightgray">
                <div class="navbar-header">
                     <a class="navbar-brand" href="#">用户管理</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                                <i class="ti-panel"></i>
								<p>欢迎【】</p>
                            </a>
                        </li>
                        <li >
                              <a href="#" >
                                <i class="ti-bell"></i>
                                <p>登录</p>
	                          </a>
                       	</li>
						<li>
                            <a href="#">
								<i class="ti-settings"></i>
								<p>注销</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        <div class="container">
            <!-- Codrops top bar -->

                <div id="container_demo" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  method="post" action="/regist/login/">
                                   {% csrf_token %}
                                <h1>登录</h1>
                                <p> 
                                    <label for="username" class="uname" data-icon="u" > 用户名 </label>
                                    <input id="username" name="username" required="required" type="text" placeholder="myusername or mymail@mail.com"/>
                                </p>
                                <p> 
                                    <label for="password" class="youpasswd" data-icon="p"> 密码 </label>
                                    <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" /> 
                                </p>
                                <p class="keeplogin"> 
									<input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" /> 
									<label for="loginkeeping">保留用户信息</label>
								</p>
                                <p class="login button"> 
                                    <input type="submit" value="登录" />
								</p>
                                <p class="change_link">
									还没有账户吗 ?
									<a href="#toregister" class="to_register">注册</a>
								</p>
                            </form>
                        </div>
						
                    </div>
                </div>  
        </div>
               <div id="Foot-Left">
                    <div style="float:right; line-height:40px; ">
                    &copy; <script>document.write(new Date().getFullYear())</script>, 制作单位：西安前站信息技术有限公司
                    </div>
                </div>
    </body>
</html>