shopsys/apps/catalog/urls.py
# encoding:utf-8
from django.conf.urls import  url
#from . import views
from shopsys.apps.catalog import  views

# urlpatterns=[
#     url(r'^$',views.index,{'template_name':'catalog/index.html'},'catalog_home'),
#     url(r'^category/(?P<category_slug>[-\w]+)/$',views.show_category,{'template_name':'catalog/category.html'},'catalog_category'),
#     url(r'^product/(?P<product_slug>[-\w]+)/$',views.show_product,{'template_name':'catalog/product.html'},'catalog_product'),
# ]

urlpatterns = [
    url(r'^', views.index,name='catalog_home'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category,name='catalog_category'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, name= 'catalog_product'),
]

shopsys/apps/plan/urls.py
from django.conf.urls import  url
from shopsys.apps.plan import  views


urlpatterns = [
    url(r'^plan/$', views.plan,name='plan'),
    url(r'^planlist/$', views.planlist,name='planlist'),
    url(r'^plandetail/$', views.plandetail,name='plandetail'),
    url(r'^contactlist/$',views.contactlist.as_view(),name='contactlist'),
    url(r'^contactdetail/(?P<pk>[0-9]+)$',views.contact_detail,name='contactdetail'),
    url(r'^planelist/$', views.PlaneList.as_view(),name='planelist'),
    url(r'^trainlist/$', views.TrainList.as_view(),name='trainlist'),
    url(r'^hotellist/$', views.HotelList.as_view(),name='hotellist'),
    url(r'^plancontact/$', views.contactview.as_view(),name='plancontact'),
]

shopsys/apps/regist/urls.py
from django.conf.urls import  url
from shopsys.apps.regist import  views


# urlpatterns=[
#     url(r'^$',views.index,{'template_name':'catalog/index.html'},'catalog_home'),
#     url(r'^category/(?P<category_slug>[-\w]+)/$',views.show_category,{'template_name':'catalog/category.html'},'catalog_category'),
#     url(r'^product/(?P<product_slug>[-\w]+)/$',views.show_product,{'template_name':'catalog/product.html'},'catalog_product'),
# ]

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^regist/$', views.regist,name='regist'),
    url(r'^login/$', views.login,name='login'),
    url(r'^user/$', views.user,name='user'),
    url(r'^maps/$', views.maps,name='map'),
    url(r'^contact/$', views.contact,name='contact'),
    url(r'^contactadd/$',views.contact_add,name='contact_add'),
    url(r'^notification/$', views.notificaiton,name='notification'),
    url(r'^logout/$', views.logout_view,name='logout'),
]

shopsys/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^regist/',include('shopsys.apps.regist.urls')),
    url(r'^catalog/',include('shopsys.apps.catalog.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shopsys/apps/plan/models.py
from django.db import models
from shopsys.apps.regist.models import Contact
from django.contrib.auth.models import User

# Create your models here.

class Plan(models.Model):
    name=models.CharField("计划单名称",max_length=50)
    fromcity=models.CharField("出发城市",max_length=30, blank=False)
    tocity=models.CharField("目的城市",max_length=30,blank=False)
    start_at = models.DateField("出发日期",blank=False)
    back_at = models.DateField("返回日期",blank=False)
    traffictype=models.IntegerField("交通工具",choices=((1,'飞机'),(2,'高铁'),(3,'普客')))
    hotletype=models.IntegerField("住宿",choices=((1,'星级宾馆'),(2,'商务宾馆')))
    target=models.CharField("目标地址",max_length=50)
    targetcoordinate = models.CharField("目标地址坐标", max_length=60)
    ifback = models.BooleanField("是否往返", choices=((1,'是'),(2,'否')))
    description=models.TextField("描述")
    is_active=models.IntegerField("计划状态",default=True)
    create_at = models.DateTimeField("创建时间", auto_now_add=True)
    update_at= models.DateTimeField("修改时间", auto_now=True)
    customer = models.ForeignKey(User)
    contact =models.ManyToManyField(Contact)

    class Meta:
        db_table='plan'
        ordering=['-create_at']
        verbose_name = '计划'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Plane_plan(models.Model):
    name = models.CharField("航班名称", max_length=50)
    companyname = models.CharField("航空公司", max_length=50)
    planetype = models.CharField("执行机型", max_length=50)
    fromcity = models.CharField("起飞站", max_length=30)
    tocity = models.CharField("落地站", max_length=30)
    start_at = models.TimeField("起飞时间")
    arrive_at = models.TimeField("落地时间")
    fromstation = models.CharField("起飞机场航站", max_length=50)
    tostation = models.CharField("落地机场航站", max_length=50)
    total_time=models.IntegerField("飞行时间")
    classtype=models.CharField("舱位", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    description = models.TextField("描述")
    is_active = models.IntegerField("订购状态", default=True)
    create_at = models.DateTimeField("创建时间", auto_now_add=True)
    update_at = models.DateTimeField("修改时间", auto_now=True)
    planid=models.ForeignKey(Plan)
    contact=models.ForeignKey(Contact)

    class Meta:
        db_table = 'plane_plan'
        verbose_name = '飞机计划'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name



class Train_plan(models.Model):
    name = models.CharField("车次", max_length=50)
    traintype = models.CharField("火车类型", max_length=20)
    fromstation = models.CharField("出发站", max_length=30)
    tostation = models.CharField("到达站", max_length=30)
    start_at = models.TimeField("发车时间")
    arrive_at = models.TimeField("到站时间")
    total_time=models.IntegerField("行驶时间")
    classtype = models.CharField("席别", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    description = models.TextField("描述")
    is_active = models.IntegerField("订购状态", default=True)
    create_at = models.DateTimeField("创建时间", auto_now_add=True)
    update_at = models.DateTimeField("修改时间", auto_now=True)
    planid=models.ForeignKey(Plan)
    contact = models.ForeignKey(Contact)

    class Meta:
        db_table = 'train_plan'
        verbose_name = '火车计划'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Hotel_plan(models.Model):
    name = models.CharField("宾馆名称", max_length=50)
    hoteltype = models.CharField("类型", max_length=20)
    address = models.CharField("地址", max_length=30)
    coordinate = models.CharField("地址坐标", max_length=60)
    classtype = models.CharField("房间类型", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    start_at = models.DateField("入住日期")
    end_at = models.DateField("离店日期")
    total_time = models.IntegerField("住宿天数")
    description = models.TextField("描述")
    is_active = models.IntegerField("订购状态", default=True)
    create_at = models.DateTimeField("创建时间", auto_now_add=True)
    update_at = models.DateTimeField("修改时间", auto_now=True)
    planid=models.ForeignKey(Plan)
    contact = models.ForeignKey(Contact)

    class Meta:
        db_table = 'hotel_plan'
        verbose_name = '住宿计划'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Plane(models.Model):
    name = models.CharField("航班名称", max_length=50)
    companyname = models.CharField("航空公司", max_length=50)
    planetype = models.CharField("执行机型", max_length=50)
    fromcity = models.CharField("起飞站", max_length=30)
    tocity = models.CharField("落地站", max_length=30)
    start_at = models.TimeField("起飞时间")
    arrive_at = models.TimeField("落地时间")
    fromstation = models.CharField("起飞机场航站", max_length=50)
    tostation = models.CharField("落地机场航站", max_length=50)
    total_time=models.IntegerField("飞行时间")
    classtype=models.CharField("舱位", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    description = models.TextField("描述")

    class Meta:
        db_table = 'plane'
        verbose_name = '航班列表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Train(models.Model):
    name = models.CharField("车次", max_length=50)
    traintype = models.CharField("火车类型", max_length=20)
    fromstation = models.CharField("出发站", max_length=30)
    tostation = models.CharField("到达站", max_length=30)
    start_at = models.TimeField("发车时间")
    arrive_at = models.TimeField("到站时间")
    total_time=models.IntegerField("行驶时间")
    classtype = models.CharField("席别", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    description = models.TextField("描述")

    class Meta:
        db_table = 'train'
        verbose_name = '火车列表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Hotel(models.Model):
    name = models.CharField("宾馆名称", max_length=50)
    city=models.CharField("城市",max_length=40)
    hoteltype = models.CharField("类型", max_length=20)
    address = models.CharField("地址", max_length=30)
    coordinate = models.CharField("地址坐标", max_length=60)
    classtype = models.CharField("房间类型", max_length=20)
    price=models.DecimalField("价格",max_digits=9,decimal_places=2,blank=True,default=0.00)
    description = models.TextField("描述")

    class Meta:
        db_table = 'hotel'
        verbose_name = '酒店列表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

shopsys/apps/catalog/forms.py
# encoding:utf-8
from django import forms
from .models import Product

class ProductAdminForm(forms.ModelForm):
    class Meta:
        model=Product
        exclude=[]
    def clean_price(self):
        if self.cleaned_data['price']<=0:
            raise forms.ValidationError('价格必须大于0')
        return self.cleaned_data['price']

shopsys/apps/regist/forms.py
# encoding:utf-8
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(CustomerForm, self).clean()
        value = cleaned_data.get("name")
        try:
            Customer.objects.get(name=value)
            self.errors["name"] = self.error_class(["%sx客户已存在" % value])
        except Customer.DoesNotExist:
            pass
        return cleaned_data

    class Meta:
        model = Customer
        exclude = {"id", }

# Create your views here.
#用户注册表单
class UserForm(forms.Form):
    email  = forms.EmailField(label="邮箱",max_length=50)
    username  = forms.CharField(label='用 户 名',max_length=50)
    password1 = forms.CharField(label='密   码',widget=forms.PasswordInput())
    password2 = forms.CharField(label='确认密码',widget=forms.PasswordInput())

#用户登录表单
class LoginForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=50)
    password = forms.CharField(label='密  码',widget=forms.PasswordInput())

#联系人表单
class ContactForm(forms.Form):
    name = forms.CharField(label="姓名", max_length=50)
    cardid = forms.CharField(label="身份证号", max_length=30)
    telephone = forms.CharField(label="手机", max_length=30)
    weixin = forms.CharField(label="微信号", max_length=50)
    age = forms.IntegerField(label="年龄")
    sex = forms.IntegerField(label="性别")

shopsys/apps/catalog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product

# Create your views here.

def index(request):
    page_title='产品分类目录'
    username= request.session.get('username',default=None)
    return render(request,'catalog/index.html',locals())

def show_category(request,category_slug):
    c = get_object_or_404(Category,slug=category_slug)
    products=c.product_set.all()
    page_title=c.name
    meta_keywords=c.meta_keywords
    meta_description=c.meta_description
    return render(request,'catalog/category.html',locals())

def show_product(request,product_slug):
    p = get_object_or_404(Product,slug=product_slug)
    categories=p.categories.filter(is_active=True)
    page_title=p.name
    meta_keywords=p.meta_keywords
    meta_description=p.meta_description
    return render(request,'catalog/products.html',locals())

shopsys/apps/regist/views.py
from django.shortcuts import render,get_object_or_404
from .forms import  ContactForm,UserForm,LoginForm
from django.http import HttpRequest,HttpResponse,HttpResponseRedirect
from shopsys.apps.regist.models import Customer,Contact
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.

# def add_regist(request):
#     page_title = '新增注册'
#     if request.method == "POST":
#         customer_form = CustomerForm(request.POST)
#         if customer_form.is_valid():
#             customer_form.save()
#         return HttpResponse("注册信息提交完成")
#
#     else:
#         customer_form = CustomerForm
#     return render(request,'regist/register.html',locals())

def regist(request):
    Method = request.method
    if Method == 'POST':
        #如果有post提交的动作，就将post中的数据赋值给uf，供该函数使用
        uf = UserForm(request.POST)
        if uf.is_valid():

            email=uf.cleaned_data['email']
            username = uf.cleaned_data['username']
            password1 = uf.cleaned_data['password1']
            password2 = uf.cleaned_data['password2']
            errors=[]
            #判断密码是否一致
            if password1==password2 :
                password=password2
            else:
                errors.append("两次输入的密码不一致!")
                return render(request, 'regist/regist.html', locals())
            #try:
            # registJudge = Customer.objects.filter(loginname = username)
            # if len(registJudge)>0 :
            #     errors.append("该用户已存在，请重新填写")
            #     return render(request,'regist/regist.html',locals())
            # #except :
            # if not errors:
            #     registAdd = Customer.objects.create(name=name,loginname=username,password=password)
            user=User.objects.create_user(username,email,password)
            response = HttpResponseRedirect('/regist/')
            return response
    else:
        uf = UserForm()
    return render (request,'regist/regist.html',locals())
#切换到Django默认的认证方式
#
def login(request):

    if request.method == 'POST':
        uf = LoginForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #对比输入的用户名和密码和数据库中是否一致
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                user_list = User.objects.get(username=username)

            #if userPassJudge:
                request.session['username'] = username
                request.session['userid']=user_list.id
                response = HttpResponseRedirect('/regist/')
                return response
            else:
                return render(request, 'regist/login.html', locals())
    else:
        uf = LoginForm()
    return render(request,'regist/login.html',locals())


def index(request):
    username = request.session.get('username', default=None)
    return render(request,'regist/dashboard.html',locals())

@login_required
def logout_view(request):
    logout(request)
    #del request.session['username']
    #del request.session['userid']
    response = HttpResponseRedirect('/regist/')
    return  response

def user(request):
    username = request.session.get('username', default=None)
    return render(request,'regist/user.html',locals())

def maps(request):
    username = request.session.get('username', default=None)
    return render(request,'regist/maps.html',locals())

def notificaiton(request):
    username = request.session.get('username', default=None)
    return render(request,'regist/notifications.html',locals())

@login_required
def contact(request):
    username = request.session.get('username', default=None)
    customerid = request.session.get('userid', default=None)
    contact_list = Contact.objects.filter(customer_id=customerid).order_by("-id")
    paginator = Paginator(contact_list, 6)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    return render(request,'regist/contact.html',locals())

def contact_add(request):

    Method = request.method
    if Method == 'POST':
        # 如果有post提交的动作，就将post中的数据赋值给uf，供该函数使用
        uf = ContactForm(request.POST)

        if uf.is_valid():
            name = uf.cleaned_data['name']
            cardid = uf.cleaned_data['cardid']
            telephone = uf.cleaned_data['telephone']
            weixin = uf.cleaned_data['weixin']
            age = uf.cleaned_data['age']
            sex = uf.cleaned_data['sex']
            print(sex)
            #description = uf.cleaned_data['description']
            customerid = request.session.get('userid', default=1)
            errors = []
            contactAdd = Contact.objects.create(name=name,cardid=cardid,telephone=telephone,weixin=weixin,age=age,sex=sex,customer_id=customerid,is_active=1)

            response = HttpResponseRedirect('/regist/contact/')
            return response
        else:
            errors=uf.errors
            return render(request, 'regist/contact.html', locals())
    else:
        uf = ContactForm()
    return render(request,'regist/contact.html',locals())

shopsys/templates/plan/plan.html
{% extends "registbase.html" %}
{% load staticfiles %}
{% block tree %}
    <div class="sidebar" data-background-color="white" data-active-color="danger">

    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->
    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="index.html" class="simple-text">
                    前站信息
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="/plan/plan/">
                        <i class="ti-panel"></i>
                        <p>我的行程</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/">
                        <i class="ti-panel"></i>
                        <p>用户视图</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/user/">
                        <i class="ti-user"></i>
                        <p>用户属性</p>
                    </a>
                </li>
                <li>
                    <a href="/plan/planlist/">
                        <i class="ti-view-list-alt"></i>
                        <p>行程列表</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/contact/">
                        <i class="ti-text"></i>
                        <p>联系人列表</p>
                    </a>
                </li>
               <li>
                    <a href="/regist/maps/">
                        <i class="ti-map"></i>
                        <p>地图</p>
                    </a>
                </li>
                <li >
                    <a href="/regist/notification/">
                        <i class="ti-bell"></i>
                        <p>小贴士</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
   
{% endblock %}
{% block content %}

<!--  业务处理区     -->
        <div class="content">
             <div class="plan_frame"> 
                 <div class="plan_main">
                      <form  method="post">
                          {% csrf_token %}
                      <div class="form-group">
                      <table width="97%">
                          <tr>
                            <td width="40%"><label>出发地</label></td>
                            <td width="15%" align="center"><label>往返</label></td>
                            <td width="40%"><label>目的地</label></td>
                          </tr>
                          <tr>
                            <td><input type="text" name="fromcity" class="form-control border-input"  list="url_list" placeholder="北京"></td>
                            <td><input type="checkbox" name="ifback" style="zoom:75%;" class="form-control border-input"  value="1"></td>
                            <td><input type="text" name="tocity" id="city_" class="form-control border-input"  list="url_list" placeholder="上海"></td>
                          </tr>
                        </table>
                        </div>

                      
                         <div class="col_plan_1">
                            <div class="form-group">
                              <label>出发时间</label>
                              <input type="date" name="start_at" class="form-control border-input" placeholder="fromtime" value="2017/04/05">
                            </div>                     
                         </div>
                         <div class="col_plan_1">
                            <div class="form-group">
                              <label>返回时间</label>
                              <input type="date" name="back_at"  class="form-control border-input" placeholder="backtime" value="2017/04/05">
                            </div>                     
                         </div>
                          <div class="col_plan_2">
                            <div class="form-group">
                            
                             <label>目的地址</label>&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static  "/img/d17.ico" %}" onClick="searchByStationName()" width="30" height="30" >
                             <img href="{% static  "/img/new_logo.png" %}" />
                                                   
                             <input id="text_" type="text" name="target" class="form-control border-input" placeholder="高新国际" >
                               <input id="result_" type="text" name="targetcoordinate" / hidden="true">
                                
                             </div>
                          </div>
                          <div class="col_plan_1">
                            <div class="form-group">
                            <label>交通</label>
                            <br/>
                              <input type="radio" name="traffictype" id="r1" value="1" checked="checked" />飞机
                              <input type="radio" name="traffictype" id="r2" value="2" /> 高铁
                              <input type="radio" name="traffictype" id="r3" value="3"  /> 普客
                            </div>
                           </div>
                           <div class="col_plan_1">
                            <div class="form-group">
                            <label>住宿</label>
                            <br/>
                              <input type="radio" name="hotletype" id="r1" value="1" checked="checked" />星级宾馆
                              <input type="radio" name="hotletype" id="r2" value="2" /> 商务酒店
                            </div>
                           </div>
                          <div class="col_plan_2">
                            <div class="form-group">
                               <label>备注</label>
                               <textarea name="description" rows="1" class="form-control border-input" placeholder="description" value="Mike">希望一切顺利.</textarea>
                             </div>
                          </div>
                          <div class="text-center">
                               <button type="" class="btn btn-info btn-fill btn-wd">方案对比</button> &nbsp;&nbsp;&nbsp;&nbsp; <button type="submit" class="btn btn-info btn-fill btn-wd">提交</button>
                          </div>
                                              
                      </form>
                      <datalist id="url_list">
                            <option label="北京" value="北京" />
                            <option label="上海" value="上海" />
                            <option label="西安" value="西安" />
                            <option label="成都" value="成都" />
                      </datalist>
                      <datalist id="back_list">
                            <option label="单程" value="单程" />
                            <option label="往返" value="往返" />                            
                      </datalist>
                  </div>
                   
               <div class="map_left">  
                        <div id="container" 
                            style="margin-top:2px; 
                                width: 100%; 
                                height: 500px; 
                                border: 1px solid gray;
                                overflow:hidden;">
                        </div>
                </div>                     
  			 </div>
    </div>

<!--  底部区域     -->
        <footer class="footer">
                     
                <div class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script>, 制作单位：西安前站信息技术有限公司
                </div>
           
        </footer>
    </div>
</div>
 

 {% endblock %}

shopsys/templates/plan/planlist.html
{% extends "registbase.html" %}
{% load staticfiles %}
{% block tree %}
	<div class="sidebar" data-background-color="white" data-active-color="danger">

    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="/regist" class="simple-text">
                    前站信息
                </a>
            </div>

            <ul class="nav">
                 <li>
                    <a href="/plan/plan/">
                        <i class="ti-panel"></i>
                        <p>我的行程</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/">
                        <i class="ti-panel"></i>
                        <p>用户视图</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/user/">
                        <i class="ti-user"></i>
                        <p>用户属性</p>
                    </a>
                </li>
                <li class="active">
                    <a href="/plan/planlist/">
                        <i class="ti-view-list-alt"></i>
                        <p>行程列表</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/contact/">
                        <i class="ti-text"></i>
                        <p>联系人</p>
                    </a>
                </li>
                 <li>
                    <a href="/regist/maps/">
                        <i class="ti-map"></i>
                        <p>地图</p>
                    </a>
                </li>
                <li>
                    <a href="/regist/notification/">
                        <i class="ti-bell"></i>
                        <p>小贴士</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
{% endblock %}
{% block content %}
          <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="content table-responsive table-full-width">
                                <table class="table table-striped">
                                    <thead>
                                        <th>ID</th>
                                    	<th>计划名称</th>
                                    	<th>出发城市</th>
                                    	<th>目的城市</th>
                                    	<th>出发日期</th>
                                        <th>到达日期</th>
                                        <th>交通方式</th>
                                        <th>宾馆类型</th>
                                        <th>是否往返</th>

                                    </thead>

                                    <tbody>
                                     {% for line in plans %}
                                        <tr>
                                        	<td>{{ line.id }}</td>
                                        	<td>{{ line.name }}</td>
                                        	<td>{{ line.fromcity }}</td>
                                        	<td>{{ line.tocity }}</td>
                                        	<td>{{ line.start_at|date:"Y-m-d" }}</td>
                                            <td>{{ line.back_at|date:"Y-m-d"  }}</td>
                                        	<td>{{ line.get_traffictype_display}}</td>
                                        	<td>{{ line.get_hotletype_display}}</td>
                                        	<td>{{ line.get_ifback_display}}</td>
                                            <td><a href="/plan/plandetail/?planid= {{ line.id }}">编辑</a></td>
                                        </tr>
                                     {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

               </div>
            </div>
        </div>
    <div class="pagination">
    <span class="step-links">
        {% if plans.has_previous %}
            <a href="?page={{ plans.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            第 {{ plans.number }} 页，共 {{ plans.paginator.num_pages }}页.
        </span>

        {% if plans.has_next %}
            <a href="?page={{ plans.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>

 {% endblock %}